# Generated by Django 2.2 on 2021-02-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmessage',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='sentmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From', to='accounts.Profile'),
        ),
    ]
