# Generated by Django 2.2 on 2021-02-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20210211_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='extra_field',
            field=models.CharField(default='marketing', max_length=220),
        ),
    ]
