# Generated by Django 2.2 on 2021-02-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210206_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar-icon.jpg', upload_to='media/profile_pics'),
        ),
    ]
