# Generated by Django 2.2 on 2021-02-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210207_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar-icon.png', upload_to='media/profile_pics'),
        ),
    ]
