# Generated by Django 2.2 on 2021-02-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loggeduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedUser',
        ),
    ]
