# Generated by Django 2.2 on 2021-02-06 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('certificate', models.CharField(max_length=220)),
                ('Audience', models.CharField(max_length=220)),
                ('length', models.IntegerField()),
                ('views', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('training_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_center.TrainingCenter')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
