# Generated by Django 2.2 on 2021-02-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='ondemand_events',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='todays_events',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='construction',
            name='upcoming_events',
            field=models.URLField(blank=True),
        ),
    ]
